In [1]:
import pandas as pd
from plotnine import *

In [2]:
df = pd.read_csv("TPM_M1146+ACT Data.csv", index_col='Locus_tag')
df

,18h,20h,22h,26h,30h,32h,34h,38h,44h,50h
Locus_tag,,,,,,,,,,
SCO3998,99.491531,81.216082,87.819865,73.784283,72.796860,68.244947,65.900336,84.170363,73.378206,76.588497
SCO3999,32.450584,32.614203,30.887831,30.533615,39.196085,37.602772,35.077389,36.162931,24.103358,28.937252
SCO4000,1.435288,2.688532,1.695832,2.887032,5.366922,1.805891,3.675716,2.254204,2.672637,3.799075
SCO4001,0.929452,1.411786,1.084093,0.885884,1.102792,1.236912,0.690545,1.235180,1.189873,1.205186
SCO4002,9.768096,9.866174,20.329238,28.817344,41.031510,37.774603,39.927043,37.556277,52.226761,19.224677
...,...,...,...,...,...,...,...,...,...,...
SCO3595,5.234269,5.320247,6.451003,4.792306,6.495986,4.735910,6.779418,4.469430,4.236168,4.609829
SCO2292,1.739743,1.600317,2.489912,1.924688,2.821893,1.666150,2.850555,2.844591,1.590855,3.094485
SCO5056,26.212698,25.261975,24.069872,18.201911,19.221481,22.764086,18.679569,16.333189,8.886684,7.144663
SCO0674,1.249837,1.112770,1.905147,1.351976,2.340343,1.721803,1.527570,1.639421,1.600027,1.312319
SCO5061,209.459259,197.850307,226.546944,151.480885,125.573151,133.576243,142.712095,198.270582,141.031304,129.687435

In [3]:
pd.read_csv("SoxR regulon.csv")

          Gene Locus tag     Effect
0    SC5G9.28c   SCO0319  Activated
1     SC5G9.29   SCO0320  Activated
2     SC5G9.30   SCO0321  Activated
3         ecaC   SCO1178  Activated
4         soxR   SCO1697  Regulator
5     SCI11.23   SCO1734  Activated
6         ecaB   SCO1909  Activated
7    SC7A8.15c   SCO2476  Activated
8    SC7A8.16c   SCO2477  Activated
9    SC7A8.17c   SCO2478  Activated
10  2SC10A7.25   SCO4021  Activated
11   SCD49.05c   SCO4264  Activated
12  SCD86A.02c   SCO4265  Activated
13        ecaD   SCO4266  Activated
14        ecaA   SCO7008  Activated

In [4]:
df1 = df.loc[["SCO0319", "SCO0320", "SCO0321", "SCO1178", "SCO1697", "SCO1734", "SCO1909", "SCO2476", "SCO2477", "SCO2478", "SCO4021", "SCO4264", "SCO4265", "SCO4266", "SCO7008"]]
df1

,18h,20h,22h,26h,30h,32h,34h,38h,44h,50h
Locus_tag,,,,,,,,,,
SCO0319,1.105248,3.268412,5.054244,1.956389,3.051779,3.186867,1.878013,3.924967,4.008956,3.199221
SCO0320,19.159191,37.321821,40.785830,14.968711,22.871691,22.516490,25.949358,22.370833,27.910451,38.471646
SCO0321,21.922768,34.189429,40.604118,11.214366,14.856411,17.606568,14.407431,14.697930,16.530183,19.694627
SCO1178,40.362029,67.273054,89.841404,38.308987,45.678466,47.795918,41.896161,47.729010,40.891347,51.827382
SCO1697,20.521055,21.182376,16.444430,12.073042,14.738705,15.083295,12.697928,11.680875,10.781661,10.088453
SCO1734,1.111096,0.753090,0.886709,0.672832,1.453228,1.214044,1.176700,0.959773,0.973229,1.568246
SCO1909,18.223067,47.391079,69.845279,38.363269,40.176108,42.239487,33.891347,34.156920,27.688973,39.922484
SCO2476,4.293236,10.624039,13.129021,7.748421,10.603998,7.063364,7.453065,5.453719,5.172846,6.385542
SCO2477,7.584190,19.113785,27.468943,8.661095,13.557067,11.427905,11.749164,9.439479,6.211793,13.121805
SCO2478,21.622515,54.319327,98.058306,40.630553,47.280023,45.331552,46.380463,49.500477,32.248912,48.641219
SCO4021,5.606942,5.940376,4.393012,2.709960,3.646099,3.130211,2.912567,2.919731,2.672637,3.016408
SCO4264,37.090595,42.745509,23.465806,25.842406,37.131966,35.621357,16.745530,10.163283,6.796397,4.507494
SCO4265,41.670978,63.194736,59.668159,22.216397,33.827224,35.150380,29.539087,26.263264,30.146710,33.325220
SCO4266,19.536192,36.121159,38.929800,15.425755,24.290654,23.360610,19.475353,21.894041,23.865750,27.638531
SCO7008,5.277683,11.585782,18.161229,10.258432,11.506680,9.939625,8.226882,8.771558,8.253103,12.643322

In [5]:
df2 = df1.stack().rename_axis(('Locus tag', 'Time')).reset_index(name='Value')
df2

    Locus tag Time      Value
0     SCO0319  18h   1.105248
1     SCO0319  20h   3.268412
2     SCO0319  22h   5.054244
3     SCO0319  26h   1.956389
4     SCO0319  30h   3.051779
..        ...  ...        ...
145   SCO7008  32h   9.939625
146   SCO7008  34h   8.226882
147   SCO7008  38h   8.771558
148   SCO7008  44h   8.253103
149   SCO7008  50h  12.643322

[150 rows x 3 columns]

In [6]:
colors = ("black", "white", "red")
lims= (0,50)
b = (5,25,50)
a = ggplot(df2, aes(x='Time', y='Locus tag')) + geom_tile(aes(fill = 'Value'))+ scale_fill_gradientn(limits= lims,colors= colors, breaks=(5,25,50),labels=("5", "25", "50"))
b = a + ggtitle('SOXR REGULON M1146 +ACT') + labs(y="Locus tag", x = "Time")

In [7]:
b.save('HeatMap1.png', width = 14, height = 14)

C:\Users\Owner\Anaconda3\lib\site-packages\plotnine\ggplot.py:729: PlotnineWarning: Saving 14 x 14 in image.
  from_inches(height, units), units), PlotnineWarning)
C:\Users\Owner\Anaconda3\lib\site-packages\plotnine\ggplot.py:730: PlotnineWarning: Filename: HeatMap1.png
  warn('Filename: {}'.format(filename), PlotnineWarning)

In [8]:
df3 = df2.copy()
df3.loc[df2["Value"] <= 5, 'Value'] = "x<=5"
df3.loc[df2["Value"] > 5, 'Value'] = "x>5"
df3

    Locus tag Time Value
0     SCO0319  18h  x<=5
1     SCO0319  20h  x<=5
2     SCO0319  22h   x>5
3     SCO0319  26h  x<=5
4     SCO0319  30h  x<=5
..        ...  ...   ...
145   SCO7008  32h   x>5
146   SCO7008  34h   x>5
147   SCO7008  38h   x>5
148   SCO7008  44h   x>5
149   SCO7008  50h   x>5

[150 rows x 3 columns]

In [9]:
a = ggplot(df3, aes(x='Time', y='Locus tag')) + geom_tile(aes(fill = 'Value')) + scale_fill_manual(values = ("red", "salmon"))
b = a + ggtitle('SOXR REGULON M1146 +ACT') + labs(y="Locus tag", x = "Time")

In [10]:
b.save('HeatMap2.png', width = 14, height = 14)

C:\Users\Owner\Anaconda3\lib\site-packages\plotnine\ggplot.py:729: PlotnineWarning: Saving 14 x 14 in image.
  from_inches(height, units), units), PlotnineWarning)
C:\Users\Owner\Anaconda3\lib\site-packages\plotnine\ggplot.py:730: PlotnineWarning: Filename: HeatMap2.png
  warn('Filename: {}'.format(filename), PlotnineWarning)

In [11]:
df1.transpose()
df4 = df1.transpose()
corr = df4.corr(method='pearson')
corr

Locus_tag,SCO0319,SCO0320,SCO0321,SCO1178,SCO1697,SCO1734,SCO1909,SCO2476,SCO2477,SCO2478,SCO4021,SCO4264,SCO4265,SCO4266,SCO7008
Locus_tag,,,,,,,,,,,,,,,
SCO0319,1.000000,0.625206,0.488843,0.683247,-0.202235,-0.100845,0.681096,0.464719,0.565682,0.716450,-0.132098,-0.314186,0.350798,0.703094,0.703082
SCO0320,0.625206,1.000000,0.768736,0.794709,0.114292,0.107519,0.646458,0.516099,0.753191,0.669915,0.293451,-0.192668,0.697051,0.898308,0.706844
SCO0321,0.488843,0.768736,1.000000,0.927876,0.617760,-0.281541,0.693276,0.644269,0.863148,0.707456,0.701708,0.292575,0.960170,0.915407,0.651109
SCO1178,0.683247,0.794709,0.927876,1.000000,0.372997,-0.228584,0.890167,0.778112,0.960881,0.913636,0.445509,0.141743,0.834743,0.930343,0.855036
SCO1697,-0.202235,0.114292,0.617760,0.372997,1.000000,-0.280245,0.117531,0.322226,0.377833,0.073796,0.953586,0.842254,0.767766,0.395160,-0.007604
SCO1734,-0.100845,0.107519,-0.281541,-0.228584,-0.280245,1.000000,-0.185194,-0.172244,-0.129762,-0.165861,-0.225989,-0.183727,-0.245964,-0.096118,-0.036714
SCO1909,0.681096,0.646458,0.693276,0.890167,0.117531,-0.185194,1.000000,0.884442,0.924968,0.959409,0.122747,0.118621,0.592207,0.773626,0.958987
SCO2476,0.464719,0.516099,0.644269,0.778112,0.322226,-0.172244,0.884442,1.000000,0.891880,0.822459,0.306520,0.395332,0.641381,0.709266,0.838580
SCO2477,0.565682,0.753191,0.863148,0.960881,0.377833,-0.129762,0.924968,0.891880,1.000000,0.927426,0.425059,0.239611,0.802438,0.880472,0.885613
SCO2478,0.716450,0.669915,0.707456,0.913636,0.073796,-0.165861,0.959409,0.822459,0.927426,1.000000,0.107450,-0.023308,0.569419,0.765170,0.924981
SCO4021,-0.132098,0.293451,0.701708,0.445509,0.953586,-0.225989,0.122747,0.306520,0.425059,0.107450,1.000000,0.689837,0.825408,0.506230,0.060534
SCO4264,-0.314186,-0.192668,0.292575,0.141743,0.842254,-0.183727,0.118621,0.395332,0.239611,-0.023308,0.689837,1.000000,0.490011,0.145102,-0.019808
SCO4265,0.350798,0.697051,0.960170,0.834743,0.767766,-0.245964,0.592207,0.641381,0.802438,0.569419,0.825408,0.490011,1.000000,0.881103,0.525700
SCO4266,0.703094,0.898308,0.915407,0.930343,0.395160,-0.096118,0.773626,0.709266,0.880472,0.765170,0.506230,0.145102,0.881103,1.000000,0.770455
SCO7008,0.703082,0.706844,0.651109,0.855036,-0.007604,-0.036714,0.958987,0.838580,0.885613,0.924981,0.060534,-0.019808,0.525700,0.770455,1.000000

In [12]:
df5 = corr.stack().rename_axis(('x', 'y')).reset_index(name='Value')
df5

           x        y     Value
0    SCO0319  SCO0319  1.000000
1    SCO0319  SCO0320  0.625206
2    SCO0319  SCO0321  0.488843
3    SCO0319  SCO1178  0.683247
4    SCO0319  SCO1697 -0.202235
..       ...      ...       ...
220  SCO7008  SCO4021  0.060534
221  SCO7008  SCO4264 -0.019808
222  SCO7008  SCO4265  0.525700
223  SCO7008  SCO4266  0.770455
224  SCO7008  SCO7008  1.000000

[225 rows x 3 columns]

In [13]:
colors = ("blue", "cornflowerblue", "white", "pink", "red")
limits=(-1,1)
breaks = (-1, -0.5, 0, 0.5, 1)
a = ggplot(df5, aes(x='x', y='y')) + geom_tile(aes(fill = 'Value'))+ scale_fill_gradientn(limits= limits,colors= colors, breaks=(-1,-0.5,0,0.5,1),labels=("-1", "-0.5", "0", "0.5", "1"))
b = a + ggtitle('SOXR REGULON M1146 +ACT') + labs(y="Locus tag", x = "Locus tag")
c = b + theme(axis_text_x = element_text(angle = 90, hjust=1))

In [14]:
c.save('HeatMap3.png', width = 14, height = 14)

C:\Users\Owner\Anaconda3\lib\site-packages\plotnine\ggplot.py:729: PlotnineWarning: Saving 14 x 14 in image.
  from_inches(height, units), units), PlotnineWarning)
C:\Users\Owner\Anaconda3\lib\site-packages\plotnine\ggplot.py:730: PlotnineWarning: Filename: HeatMap3.png
  warn('Filename: {}'.format(filename), PlotnineWarning)